app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(lambda_r = "1,2,3,4")
app$snapshot()
app$setInputs(tau_r = "6,7,8,9")
app$snapshot()
app$setInputs(theta_r = "2,3,4,5")
app$snapshot()
app$setInputs(uselambda_f = TRUE)
app$snapshot()
app$setInputs(lambda_f = "3,4,5,6")
app$snapshot()
app$setInputs(usetau_f = TRUE)
app$snapshot()
app$setInputs(tau_f = "5,6,7,8")
app$snapshot()
app$setInputs(usepropsel = TRUE)
app$snapshot()
app$setInputs(legend_r = "test")
app$setInputs(legend_f = "test2")
app$snapshot()
