# usethis::use_package("shiny")
# usethis::use_package("pkgload")
# usethis::use_package("shinydashboard")
# usethis::use_package("shinyjs")
# usethis::use_package("shinyWidgets")
# usethis::use_package("shinyMatrix")
# usethis::use_package("rsconnect")
# usethis::use_package("shinytest")

#pkgload::load_all(".")
rsconnect::deployApp()
